spring:
  application:
   name: mybatis-plus
  datasource:
      # ????????useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      url: jdbc:mysql://localhost:3306/javaclass
      username: root
      password: Dew2339
      driver-class-name: com.mysql.cj.jdbc.Driver

      # ???? Druid ?????????
      type: com.alibaba.druid.pool.DruidDataSource

      # Druid ????????
      druid:
        # ??????????????
        initial-size: 5
        min-idle: 5
        max-active: 20
        # ?????????????????
        max-wait: 60000
        # ?????????????????????????????
        time-between-eviction-runs-millis: 60000
        # ??????????????????
        min-evictable-idle-time-millis: 300000

        # ??????????
        # WebStatFilter?????web-jdbc???????
        web-stat-filter:
          enabled: true
          url-pattern: "/*"
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        # StatViewServlet??????????
        stat-view-servlet:
          enabled: true
          url-pattern: "/druid/*"
          # ???????????
          login-username: admin
          login-password: admin123
          reset-enable: false # ??????
        # ??????
        filter:
          stat:
            enabled: true
            log-slow-sql: true # ???SQL
            slow-sql-millis: 2000 # ?SQL?????????
          wall:
            enabled: true # ??SQL????????SQL??
